name: e_commerce_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

# De
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.0.0
  lottie: ^3.1.2
  google_fonts: ^6.2.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_core: ^3.3.0
  provider: ^6.1.2
  flutter_screenutil: ^5.9.0
  iconly: ^1.0.1
  #carousel_slider: ^4.0.1
  flutter_bloc: ^8.1.6
  injectable: ^2.4.2
  get_it: ^7.7.0
  internet_connection_checker: ^1.0.0+1
  http: ^1.2.2
  shared_preferences: ^2.2.3
  dio: ^5.7.0
  dartz: ^0.10.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  injectable_generator: ^2.6.2
  permission_handler: ^10.0.0

  
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/images/laptops.png
#  fonts:
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/Poppins-Black.ttf
#        - asset: assets/fonts/Poppins-BlackItalic.ttf
#        - asset: assets/fonts/Poppins-Bold.ttf
#        - asset: assets/fonts/Poppins-BoldItalic.ttf
#        - asset: assets/fonts/Poppins-ExtraBold.ttf
#        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
#        - asset: assets/fonts/Poppins-ExtraLight.ttf
#        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
#        - asset: assets/fonts/Poppins-Italic.ttf
#        - asset: assets/fonts/Poppins-Light.ttf
#        - asset: assets/fonts/Poppins-LightItalic.ttf
#        - asset: assets/fonts/Poppins-Medium.ttf
#        - asset: assets/fonts/Poppins-MediumItalic.ttf
#        - asset: assets/fonts/Poppins-Regular.ttf
#        - asset: assets/fonts/Poppins-SemiBold.ttf
#        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
#        - asset: assets/fonts/Poppins-Thin.ttf
#        - asset: assets/fonts/Poppins-ThinItalic.ttf
#
#

